### ISSUE TITLE
require 'pry' outside dev env throws error

### ISSUE THREAD

**Issue by Tuxified** [jmmastey/bundler-stats#2]
Hi,

Thanks for this gem, it saved me a trip down the rabbit hole to find which gem blocked my `bundle update nokogiri` (like described in https://olivierlacan.com/posts/why-wont-bundle-update/ ). However when I first tried this gem, I got an exception as [pry was required](https://github.com/jmmastey/bundler-stats/blob/master/lib/bundler/stats/tree.rb#L1) but it's only a dependency for development, not when running/using the gem (`bundle-stats versions nokogiri` worked perfectly after I removed that line)

I'm not sure what the correct fix would be, either removing that line or making sure it's only required for development purposes?

A snippet of the stack trace :

```
$ bundle-stats versions nokogiri
/Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats/tree.rb:1:in `require': cannot load such file -- pry (LoadError)
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats/tree.rb:1:in `<top (required)>'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats.rb:2:in `require_relative'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats.rb:2:in `<top (required)>'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats/cli.rb:5:in `require'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/lib/bundler/stats/cli.rb:5:in `<top (required)>'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/bin/bundle-stats:9:in `require'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/gems/bundler-stats-1.1.0/bin/bundle-stats:9:in `<top (required)>'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/bin/bundle-stats:23:in `load'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/bin/bundle-stats:23:in `<main>'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
  from /Users/toncigalic/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

I hope my description makes sense and thanks again for this gem, it's really useful :D

**Comment by jmmastey** [comment]
Great catch @Tuxified, thanks for this. I've pushed 1.1.1 to fix this issue.
