### ISSUE TITLE
gems.rb and gems.locked

### ISSUE THREAD

**Issue by svoop** [jmmastey/bundler-stats#26]
It would be great if this useful gem supported the alternative gemfile names as well:

* `gems.rb` (alternative for `Gemfile`)
* `gems.locked` (alternative for `Gemfile.lock`)

These [alternative names were introduced in 2017](https://depfu.com/blog/2017/09/06/gemfiles-new-clothes).

**Comment by svoop** [comment]
@jmmastey I'll see if I get to it these days, kinda busy as well upping a gazillion gems. :-)

**Comment by svoop** [comment]
@jmmastey [Here's a PR](https://github.com/jmmastey/bundler-stats/pull/27) for the alternative gems.rb/gems.locked names. I haven't refactored it, just bolted them on top. However, I've also noted that the current dependency on thor 1.19 causes update blockers when you have other gems using Thor in the bundle. I've therefore relaxed the dependency and added  a bit which makes sure your CLI tool exists as expected when unknown commands are used.

Thanks for considering to merge and cutting a release!

**Comment by jmmastey** [comment]
Closed via https://github.com/jmmastey/bundler-stats/pull/27
