### ISSUE TITLE
Extremely long gem names break the tables

### ISSUE THREAD

**Issue by olivierlacan** [jmmastey/bundler-stats#5]
![image](https://user-images.githubusercontent.com/65950/37537061-c92645f4-2922-11e8-89d7-14de377e6a64.png)

Maybe you're right. A smarter table layout generator could be warranted. 😄

**Comment by jmmastey** [comment]
Yeah, I mean it's a visual thing and probably not a deal breaker anyway, but at the least a simple `compute_column_length` is probably warranted.
