### ISSUE TITLE
Unknown gem tzinfo-data (ArgumentError) 

### ISSUE THREAD

**Issue by olivierlacan** [jmmastey/bundler-stats#7]
Just tried to install and run bundler-stats on Ruby 2.4.2 under macOS and instantly got this error when running it without arguments:

```
$ bundle-stats
/Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/tree.rb:38:in `transitive_dependencies': Unknown gem tzinfo-data (ArgumentError)
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/tree.rb:13:in `summarize'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/calculator.rb:65:in `block in gem_stats'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/calculator.rb:64:in `map'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/calculator.rb:64:in `gem_stats'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/calculator.rb:40:in `stats'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/lib/bundler/stats/cli.rb:18:in `stats'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-stats-1.1.2/bin/bundle-stats:11:in `<top (required)>'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/bin/bundle-stats:23:in `load'
	from /Users/olivierlacan/.rbenv/versions/2.4.2/bin/bundle-stats:23:in `<main>'
```

It feels familiar but I can remember why. This gem appears in the `DEPENDENCIES` list in the `Gemfile.lock` of the app I'm working with but not anywhere else. Might be a merge conflict artifact. 

Although when running `bundle install` this message appears: 
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.

Seems like it might be what's confusing bundler-stats. It's a listed gem that isn't installed on the platform I'm running from on purpose.

**Comment by jmmastey** [comment]
I think I've got the issue. I tried a gemfile like this:

```
gem "rails", platform: :jruby
gem "rspec"
```

After a bundle install, my lockfile is _missing_ specs for the wrong-platform gem:

```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rspec (3.8.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
    rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.0)

PLATFORMS
  ruby

DEPENDENCIES
  rails
  rspec

BUNDLED WITH
   1.16.1
```

Since bundler stats depends on the Bundler DSL for finding transitive dependencies, an excluded dependency would be missed entirely. The following line is exploding on that issue:

https://github.com/jmmastey/bundler-stats/blob/master/lib/bundler/stats/tree.rb#L38

For resolutions, I don't think we can change how bundler itself deals with the dependencies. I think that line (and another nearly identical one above it) could be changed to a warning with a message something like:

```
The dependency `tzinfo-data` wasn't found. It may not be present in your Gemfile.lock. This often happens when a dependency isn't installed on your platform.
```

But keep running. Thoughts?

**Comment by jmmastey** [comment]
@olivierlacan what do you think about this approach? It wouldn't take me long to add.
