### ISSUE TITLE
Doesn't work with bundler 2.0

### ISSUE THREAD

**Issue by localhostdotdev** [jmmastey/bundler-stats#8]
```
Unable to activate bundler-stats-1.1.2, because bundler-2.0.1 conflicts with bundler (~> 1.9) (Gem::ConflictError)
```

May still work with bundler 2: https://github.com/bundler/bundler/releases

**Comment by localhostdotdev** [comment]
Tried it and it seems to works fine with bundler 2: https://github.com/localhostdotdev/bundler-stats/commit/9f506b0676cbaa93512d7c36106aac65be4aed49

**Comment by jmmastey** [comment]
Cool, released https://rubygems.org/gems/bundler-stats/versions/1.2.0 to fix this. Let me know if you have any issues, and thanks for the report.
